# Ecuaciones Lineales

### Trabajo realizado por: Jesus Enrique Lugo Ramirez
### Graficación Computacional
### Profesora: Hazem Álvarez Rodríguez
### Clase del 11 de noviembre de 2024

## Ejemplo

In [4]:
import numpy as np

In [5]:
A4 = np.matrix([[3,2,-1],[2,-2,4],[-1,0.5,-1]])
b4 = np.matrix([[1],[-2],[0]])

In [6]:
x4 = (A4**-1)*b4
determinante4 = np.linalg.det(A4)

In [7]:
# Mostrar los resultados
print("Forma matricial A x = b:")
print("Matriz A:")
print(A4)
print("Vector b:")
print(b4)
print("\nDeterminante de A:", determinante4)
print("\nValor de x:")
print(x4)

Forma matricial A x = b:
Matriz A:
[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
Vector b:
[[ 1]
 [-2]
 [ 0]]

Determinante de A: -3.0000000000000036

Valor de x:
[[ 1.]
 [-2.]
 [-2.]]


## Actividad

### 1. A = (9)

In [8]:
A = np.matrix([[9]])

print("this is A\n",A)
det = np.linalg.det(A)
print("this is the determinante\n",det)

this is A
 [[9]]
this is the determinante
 9.000000000000002


### 2. B = ([4 -1]  [-2 0])

In [9]:
A = np.matrix([[4, -1],[-2, 0]])

print("this is A\n",A)
det = np.linalg.det(A)
print("this is the determinante\n",det)


this is A
 [[ 4 -1]
 [-2  0]]
this is the determinante
 -2.0


### 2. C = ([5 0 2]  [3 1 1] [0 1 2])

In [10]:
A = np.matrix([[5, 0, 0], [3, 1, 1],[0, 1, 2]])

print("this is A\n",A)
det = np.linalg.det(A)
print("this is the determinante\n",det)

this is A
 [[5 0 0]
 [3 1 1]
 [0 1 2]]
this is the determinante
 4.999999999999999
